# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 15:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_consulta', models.CharField(max_length=100)),
                ('antecedentes', models.CharField(max_length=100)),
                ('medicamentos_en_uso', models.CharField(max_length=60)),
                ('alergias', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Asistente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('tipo_identificacion', models.CharField(choices=[('CC', 'Cedula de ciudadania'), ('CE', 'Cedula de extranjeria'), ('PA', 'Pasaporte'), ('TI', 'Tarjeta de identidad'), ('RC', 'Registro civil')], max_length=2)),
                ('direccion', models.TextField()),
                ('telefono_fijo', models.CharField(max_length=12)),
                ('telefono_celular', models.CharField(max_length=12)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.DateTimeField()),
                ('hora_fin', models.DateTimeField()),
                ('actividad', models.TextField()),
                ('observacion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30)),
                ('num_diente', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Diente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_diente', models.IntegerField()),
                ('CaraDiente1', models.CharField(choices=[('OC', 'Oclusal'), ('DI', 'Distal'), ('ME', 'Mesial'), ('LI', 'Lingual'), ('GI', 'Gingival')], max_length=2)),
                ('CaraDiente2', models.CharField(choices=[('OC', 'Oclusal'), ('DI', 'Distal'), ('ME', 'Mesial'), ('LI', 'Lingual'), ('GI', 'Gingival')], max_length=2)),
                ('CaraDiente3', models.CharField(choices=[('OC', 'Oclusal'), ('DI', 'Distal'), ('ME', 'Mesial'), ('LI', 'Lingual'), ('GI', 'Gingival')], max_length=2)),
                ('CaraDiente4', models.CharField(choices=[('OC', 'Oclusal'), ('DI', 'Distal'), ('ME', 'Mesial'), ('LI', 'Lingual'), ('GI', 'Gingival')], max_length=2)),
                ('CaraDiente5', models.CharField(choices=[('OC', 'Oclusal'), ('DI', 'Distal'), ('ME', 'Mesial'), ('LI', 'Lingual'), ('GI', 'Gingival')], max_length=2)),
                ('id_diagnostico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HC.Diagnostico')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('tipo_identificacion', models.CharField(choices=[('CC', 'Cedula de ciudadania'), ('CE', 'Cedula de extranjeria'), ('PA', 'Pasaporte'), ('TI', 'Tarjeta de identidad'), ('RC', 'Registro civil')], max_length=2)),
                ('resolucion', models.IntegerField()),
                ('direccion', models.TextField()),
                ('telefono_fijo', models.CharField(max_length=12)),
                ('telefono_celular', models.CharField(max_length=12)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('id_doctor', models.ManyToManyField(to='HC.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Evolucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField()),
                ('id_diente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HC.Diente')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioNoDisponible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.DateField()),
                ('hora_fin', models.DateField()),
                ('dia_semana', models.CharField(choices=[('LU', 'Lunes'), ('MA', 'Martes'), ('MI', 'Miercoles'), ('JU', 'Jueves'), ('VI', 'Viernes'), ('SA', 'Sabado')], max_length=2)),
                ('id_doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HC.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('tipo_identificacion', models.CharField(choices=[('CC', 'Cedula de ciudadania'), ('CE', 'Cedula de extranjeria'), ('PA', 'Pasaporte'), ('TI', 'Tarjeta de identidad'), ('RC', 'Registro civil')], max_length=2)),
                ('direccion', models.TextField()),
                ('telefono_fijo', models.CharField(max_length=12)),
                ('telefono_celular', models.CharField(max_length=12)),
                ('departamento', models.CharField(choices=[('CU', 'Cundinamarca'), ('BO', 'Boyaca'), ('VA', 'Valle del Cauca'), ('AN', 'Antioquia'), ('ME', 'Meta')], max_length=2)),
                ('ciudad', models.CharField(choices=[('BO', 'Bogota'), ('TU', 'Tunja'), ('CA', 'Cali'), ('ME', 'Medellin'), ('VI', 'Villavicencio')], max_length=2)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.IntegerField()),
                ('nacionalidad', models.CharField(max_length=30)),
                ('rh', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=2)),
                ('nombres_acuediente', models.CharField(max_length=50)),
                ('telefono_acuediente', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=30)),
                ('id_user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='evolucion',
            name='id_paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HC.Paciente'),
        ),
        migrations.AddField(
            model_name='especialidad',
            name='id_tratamiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HC.Tratamiento'),
        ),
        migrations.AddField(
            model_name='diente',
            name='id_paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HC.Paciente'),
        ),
        migrations.AddField(
            model_name='diente',
            name='id_tratamiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HC.Tratamiento'),
        ),
        migrations.AddField(
            model_name='cita',
            name='id_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HC.Doctor'),
        ),
        migrations.AddField(
            model_name='cita',
            name='id_paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HC.Paciente'),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='id_paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HC.Paciente'),
        ),
    ]
